"""Animal

Revision ID: 5f593e04ee8a
Revises: e6f5e0b9e436
Create Date: 2026-06-17 16:54:59.415655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f593e04ee8a'
down_revision: Union[str, Sequence[str], None] = 'e6f5e0b9e436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animaux', sa.Column('prix_vente', sa.Integer(), nullable=True))
    op.add_column('animaux', sa.Column('date_vente', sa.Date(), nullable=True))
    op.add_column('animaux', sa.Column('client_acheteur', sa.String(length=32), nullable=True))
    op.add_column('animaux', sa.Column('note_vente', sa.Text(), nullable=True))
    op.alter_column('animaux', 'type_espece',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('animaux', 'identification',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('animaux', 'race',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('animaux', 'provenance',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('animaux', 'prix_achat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animaux', 'prix_achat',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('animaux', 'provenance',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('animaux', 'race',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('animaux', 'identification',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('animaux', 'type_espece',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('animaux', 'note_vente')
    op.drop_column('animaux', 'client_acheteur')
    op.drop_column('animaux', 'date_vente')
    op.drop_column('animaux', 'prix_vente')
    # ### end Alembic commands ###
