"""Initial

Revision ID: e6f5e0b9e436
Revises: 
Create Date: 2026-06-15 15:37:44.569071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f5e0b9e436'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('VACCINATION', 'PESEE', 'NETTOYAGE', 'MORTALITE', 'WATER_QUALITY', 'BEA', 'COMPTABLE', 'STOCK', 'TEMPERATURE', 'ODONI', 'REPRODUCTION', 'COMPOST', 'SURPOPULATION', 'SANTE', name='alerttypeenum'), nullable=False),
    sa.Column('niveau', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertniveauenum'), nullable=False),
    sa.Column('parametre', sa.String(length=100), nullable=False),
    sa.Column('seuil_min', sa.Integer(), nullable=True),
    sa.Column('seuil_max', sa.Integer(), nullable=True),
    sa.Column('fenetre_jours', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('action_suggestee', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('espece', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bien_etre_criteres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ponderation', sa.Float(), nullable=False),
    sa.Column('seuil_alerte', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('DECRETS_VERTS', 'FUMIER', 'MIXTE', name='composttype'), nullable=False),
    sa.Column('date_demarrage', sa.Date(), nullable=False),
    sa.Column('volume_initial', sa.Float(), nullable=False),
    sa.Column('volume_final', sa.Float(), nullable=True),
    sa.Column('date_maturite_estimee', sa.Date(), nullable=True),
    sa.Column('date_maturite_reelle', sa.Date(), nullable=True),
    sa.Column('utilisation_finale', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enclos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('ENCLOS', 'BASSIN', 'PATURAGE', 'CAGE', 'BAC', name='enclostype'), nullable=False),
    sa.Column('longueur', sa.Float(), nullable=False),
    sa.Column('largeur', sa.Float(), nullable=False),
    sa.Column('hauteur', sa.Float(), nullable=True),
    sa.Column('localisation_gps', sa.String(length=64), nullable=True),
    sa.Column('zone', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('maladies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('especes_concernees', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vaccin_disponible', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('rations_alimentaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('proteines_pourcent', sa.Float(), nullable=True),
    sa.Column('energie_kcal', sa.Float(), nullable=True),
    sa.Column('calcium_g', sa.Float(), nullable=True),
    sa.Column('phosphore_g', sa.Float(), nullable=True),
    sa.Column('quantite_recommandee_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_croissance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=False),
    sa.Column('age_jours', sa.Integer(), nullable=False),
    sa.Column('poids_min', sa.Float(), nullable=False),
    sa.Column('poids_moyen', sa.Float(), nullable=False),
    sa.Column('poids_max', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_generales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('type_reference', sa.String(length=50), nullable=False),
    sa.Column('donnees', sa.JSON(), nullable=False),
    sa.Column('confiance', sa.Float(), nullable=True),
    sa.Column('nombre_donnees', sa.Integer(), nullable=True),
    sa.Column('date_derniere_mise_a_jour', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_nutrition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('proteines_pourcent', sa.Float(), nullable=True),
    sa.Column('energie_kcal', sa.Float(), nullable=True),
    sa.Column('calcium_g', sa.Float(), nullable=True),
    sa.Column('phosphore_g', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_seuils',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('parametre', sa.String(length=100), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('seuil_min', sa.Float(), nullable=True),
    sa.Column('seuil_max', sa.Float(), nullable=True),
    sa.Column('seuil_optimal_min', sa.Float(), nullable=True),
    sa.Column('seuil_optimal_max', sa.Float(), nullable=True),
    sa.Column('niveau_alerte', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_vaccination',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('maladie', sa.String(length=100), nullable=False),
    sa.Column('age_recommande_jours', sa.Integer(), nullable=True),
    sa.Column('rappel_mois', sa.Integer(), nullable=True),
    sa.Column('saison_recommandee', sa.String(length=50), nullable=True),
    sa.Column('vaccin_nom', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'BOVIN_ADMIN', 'BOVIN_TECHNICIEN', 'BOVIN_OBSERVATEUR', 'OVIN_ADMIN', 'OVIN_TECHNICIEN', 'OVIN_OBSERVATEUR', 'CAPRIN_ADMIN', 'CAPRIN_TECHNICIEN', 'CAPRIN_OBSERVATEUR', 'AVICOLE_ADMIN', 'AVICOLE_TECHNICIEN', 'AVICOLE_OBSERVATEUR', 'PISCICOLE_ADMIN', 'PISCICOLE_TECHNICIEN', 'PISCICOLE_OBSERVATEUR', 'APICULTURE_ADMIN', 'APICULTURE_TECHNICIEN', 'APICULTURE_OBSERVATEUR', 'ENTOMOCULTURE_ADMIN', 'ENTOMOCULTURE_TECHNICIEN', 'ENTOMOCULTURE_OBSERVATEUR', 'VETERINAIRE', 'RESPONSABLE_ENCLOS', 'COMPTABLE', 'VISION_GLOBALE', name='roleenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ruches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identification', sa.String(length=50), nullable=False),
    sa.Column('emplacement', sa.String(length=255), nullable=True),
    sa.Column('date_installation', sa.Date(), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.Enum('ACTIVE', 'ORPHELINE', 'EN_ESSIMAGE', 'MORTE', name='statutrucheenum'), nullable=True),
    sa.Column('nombre_cadres', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_user_id'), 'action_logs', ['user_id'], unique=False)
    op.create_table('animaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_espece', sa.String(length=50), nullable=False),
    sa.Column('identification', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=False),
    sa.Column('sexe', sa.Enum('MALE', 'FEMELLE', 'HERMAPHRODITE', name='sexeenum'), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('prix_achat', sa.Float(), nullable=True),
    sa.Column('enclos_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('VIVANT', 'VENDU', 'DECEDE', 'TRANSFERE', name='statutanimalenum'), nullable=True),
    sa.Column('type_production', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animaux_identification'), 'animaux', ['identification'], unique=True)
    op.create_table('avicoles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identification', sa.String(length=100), nullable=False),
    sa.Column('espece', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=False),
    sa.Column('type_production', sa.Enum('VIANDE', 'PONTE', 'REPRODUCTION', 'MIXTE', name='typeproductionavicoleenum'), nullable=False),
    sa.Column('quantite_initial', sa.Integer(), nullable=False),
    sa.Column('quantite_actuelle', sa.Integer(), nullable=False),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('prix_achat_unitaire', sa.Float(), nullable=True),
    sa.Column('prix_achat_total', sa.Float(), nullable=True),
    sa.Column('production_viande', sa.Boolean(), nullable=True),
    sa.Column('production_reproduction', sa.Boolean(), nullable=True),
    sa.Column('production_ponte', sa.Boolean(), nullable=True),
    sa.Column('oeufs_pondus_total', sa.Integer(), nullable=True),
    sa.Column('oeufs_pondus_jour', sa.Integer(), nullable=True),
    sa.Column('poids_oeufs_total', sa.Float(), nullable=True),
    sa.Column('poids_oeufs_moyen', sa.Float(), nullable=True),
    sa.Column('mortalite_total', sa.Integer(), nullable=True),
    sa.Column('taux_mortalite', sa.Float(), nullable=True),
    sa.Column('vendus_total', sa.Integer(), nullable=True),
    sa.Column('abattus_total', sa.Integer(), nullable=True),
    sa.Column('date_derniere_vente', sa.Date(), nullable=True),
    sa.Column('poids_moyen_initial', sa.Float(), nullable=True),
    sa.Column('poids_moyen_actuel', sa.Float(), nullable=True),
    sa.Column('poids_total_viande', sa.Float(), nullable=True),
    sa.Column('enclos_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'VENDU', 'ABATTU', 'DECEDE', name='statutlotavicoleenum'), nullable=True),
    sa.Column('date_fermeture', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avicoles_identification'), 'avicoles', ['identification'], unique=True)
    op.create_table('bien_etre_indices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enclos_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('indice_global', sa.Float(), nullable=False),
    sa.Column('indice_proprete', sa.Float(), nullable=True),
    sa.Column('indice_acces_eau', sa.Float(), nullable=True),
    sa.Column('indice_densite', sa.Float(), nullable=True),
    sa.Column('indice_comportement', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bien_etre_indices_date'), 'bien_etre_indices', ['date'], unique=False)
    op.create_index(op.f('ix_bien_etre_indices_enclos_id'), 'bien_etre_indices', ['enclos_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('enclos_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('roi_config', sa.Text(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donnees_experimentales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('entite_type', sa.String(length=50), nullable=False),
    sa.Column('entite_id', sa.Integer(), nullable=False),
    sa.Column('est_essai', sa.Boolean(), nullable=True),
    sa.Column('est_production', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_essai', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entomoculture_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identification', sa.String(length=100), nullable=False),
    sa.Column('espece', sa.String(length=100), nullable=False),
    sa.Column('stade_actuel', sa.Enum('OEUF', 'LARVE', 'PREPUPE', 'PUPE', 'ADULTE', name='stadeinsecteenum'), nullable=False),
    sa.Column('date_arrivee', sa.Date(), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('prix_achat', sa.Float(), nullable=True),
    sa.Column('poids_initial', sa.Float(), nullable=True),
    sa.Column('quantite_estimative', sa.Integer(), nullable=True),
    sa.Column('enclos_id', sa.Integer(), nullable=True),
    sa.Column('type_production', sa.Enum('LARVES', 'REPRODUCTION', 'OEUFS', name='typeproductioninsecteenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entomoculture_lots_identification'), 'entomoculture_lots', ['identification'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_types', sa.JSON(), nullable=True),
    sa.Column('min_niveau', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertniveauenum'), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('pieges_odoni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emplacement', sa.String(length=255), nullable=True),
    sa.Column('enclos_id', sa.Integer(), nullable=True),
    sa.Column('compost_id', sa.Integer(), nullable=True),
    sa.Column('date_installation', sa.Date(), nullable=False),
    sa.Column('type_piege', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compost_id'], ['composts.id'], ),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recoltes_miel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruche_id', sa.Integer(), nullable=False),
    sa.Column('date_recolte', sa.Date(), nullable=False),
    sa.Column('poids_kg', sa.Float(), nullable=False),
    sa.Column('qualite', sa.String(length=50), nullable=True),
    sa.Column('taux_eau', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ruche_id'], ['ruches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references_hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('espece', sa.String(length=50), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('parametre', sa.String(length=100), nullable=False),
    sa.Column('valeur_estimee', sa.Float(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('validee', sa.Boolean(), nullable=True),
    sa.Column('date_validation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruche_id', sa.Integer(), nullable=False),
    sa.Column('annee_naissance', sa.Integer(), nullable=False),
    sa.Column('origine', sa.String(length=255), nullable=True),
    sa.Column('date_remplacement', sa.Date(), nullable=True),
    sa.Column('est_marquee', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ruche_id'], ['ruches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retournements_compost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compost_id', sa.Integer(), nullable=False),
    sa.Column('date_retournement', sa.Date(), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('temperature_avant', sa.Float(), nullable=True),
    sa.Column('temperature_apres', sa.Float(), nullable=True),
    sa.Column('humidite_avant', sa.Float(), nullable=True),
    sa.Column('humidite_apres', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compost_id'], ['composts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vaccins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('fabricant', sa.String(length=100), nullable=True),
    sa.Column('lot', sa.String(length=50), nullable=True),
    sa.Column('maladie_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['maladie_id'], ['maladies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_qualities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enclos_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('oxygene_dissous', sa.Float(), nullable=True),
    sa.Column('ammoniac', sa.Float(), nullable=True),
    sa.Column('nitrites', sa.Float(), nullable=True),
    sa.Column('nitrates', sa.Float(), nullable=True),
    sa.Column('conductivite', sa.Float(), nullable=True),
    sa.Column('turbidite', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('alerte_generee', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_qualities_enclos_id'), 'water_qualities', ['enclos_id'], unique=False)
    op.create_index(op.f('ix_water_qualities_timestamp'), 'water_qualities', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('VACCINATION', 'PESEE', 'NETTOYAGE', 'MORTALITE', 'WATER_QUALITY', 'BEA', 'COMPTABLE', 'STOCK', 'TEMPERATURE', 'ODONI', 'REPRODUCTION', 'COMPOST', 'SURPOPULATION', 'SANTE', name='alerttypeenum'), nullable=False),
    sa.Column('niveau', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertniveauenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('espece', sa.String(length=50), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('enclos_id', sa.Integer(), nullable=True),
    sa.Column('compost_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('date_alerte', sa.DateTime(), nullable=False),
    sa.Column('date_limite', sa.DateTime(), nullable=True),
    sa.Column('date_lue', sa.DateTime(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=True),
    sa.Column('est_traitee', sa.Boolean(), nullable=True),
    sa.Column('action_suggestee', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('utilisateur_traitement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['compost_id'], ['composts.id'], ),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_traitement_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alimentations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('lot_entomo_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('poids_nourriture', sa.Float(), nullable=False),
    sa.Column('type_nourriture', sa.String(length=100), nullable=False),
    sa.Column('composition', sa.String(length=255), nullable=True),
    sa.Column('cout', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['lot_entomo_id'], ['entomoculture_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimentations_animal_id'), 'alimentations', ['animal_id'], unique=False)
    op.create_index(op.f('ix_alimentations_date'), 'alimentations', ['date'], unique=False)
    op.create_index(op.f('ix_alimentations_lot_entomo_id'), 'alimentations', ['lot_entomo_id'], unique=False)
    op.create_table('avicoles_mortalites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nombre_morts', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['avicoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avicoles_productions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nombre_oeufs', sa.Integer(), nullable=True),
    sa.Column('poids_oeufs_kg', sa.Float(), nullable=True),
    sa.Column('nombre_morts', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['avicoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bovins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_laitiere', sa.Boolean(), nullable=True),
    sa.Column('production_viande', sa.Boolean(), nullable=True),
    sa.Column('production_reproduction', sa.Boolean(), nullable=True),
    sa.Column('lactation_en_cours', sa.Boolean(), nullable=True),
    sa.Column('production_lait_quotidienne', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['animaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caprins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_viande', sa.Boolean(), nullable=True),
    sa.Column('production_reproduction', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['animaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comptages_odoni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('piege_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=False),
    sa.Column('espece', sa.String(length=100), nullable=True),
    sa.Column('methode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['piege_id'], ['pieges_odoni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comptages_odoni_timestamp'), 'comptages_odoni', ['timestamp'], unique=False)
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categorie', sa.Enum('ACHAT_ANIMAUX', 'ACHAT_OEUFS', 'ALIMENTATION', 'VACCINS_SOINS', 'EQUIPEMENT', 'PERSONNEL', 'EAU_ELECTRICITE', 'ENTRETIEN', 'COMPOSTAGE', 'TRANSPORT', 'FRAIS_DIVERS', name='categoriedepenseenum'), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('lot_entomo_id', sa.Integer(), nullable=True),
    sa.Column('piece_jointe_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['lot_entomo_id'], ['entomoculture_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entomoculture_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('stade_debut', sa.Enum('OEUF', 'LARVE', 'PREPUPE', 'PUPE', 'ADULTE', name='stadeinsecteenum'), nullable=False),
    sa.Column('stade_fin', sa.Enum('OEUF', 'LARVE', 'PREPUPE', 'PUPE', 'ADULTE', name='stadeinsecteenum'), nullable=True),
    sa.Column('production_grammes', sa.Float(), nullable=True),
    sa.Column('taux_mortalite', sa.Float(), nullable=True),
    sa.Column('substrat_utilise', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['entomoculture_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortalites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date_mort', sa.Date(), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('autopsie_realisee', sa.Boolean(), nullable=True),
    sa.Column('poids_cadavre', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mortalites_animal_id'), 'mortalites', ['animal_id'], unique=False)
    op.create_table('ovins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_viande', sa.Boolean(), nullable=True),
    sa.Column('production_reproduction', sa.Boolean(), nullable=True),
    sa.Column('production_laine', sa.Boolean(), nullable=True),
    sa.Column('qualite_laine', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['animaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piscicoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_viande', sa.Boolean(), nullable=True),
    sa.Column('production_reproduction', sa.Boolean(), nullable=True),
    sa.Column('taille_moyenne', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['animaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recettes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categorie', sa.Enum('VENTE_ANIMAUX_VIVANTS', 'VENTE_VIANDE', 'VENTE_LAIT', 'VENTE_LAINE', 'VENTE_OEUFS', 'VENTE_LARVES', 'VENTE_COMPOST', 'VENTE_FUMIER', 'SUBVENTIONS', 'AUTRES', name='categorierecetteenum'), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('quantite', sa.Float(), nullable=True),
    sa.Column('prix_unitaire', sa.Float(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('lot_entomo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['lot_entomo_id'], ['entomoculture_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('maladie_id', sa.Integer(), nullable=False),
    sa.Column('vaccin_id', sa.Integer(), nullable=True),
    sa.Column('date_prevue', sa.Date(), nullable=False),
    sa.Column('date_realisee', sa.Date(), nullable=True),
    sa.Column('dose', sa.String(length=50), nullable=True),
    sa.Column('rappel_necessaire', sa.Boolean(), nullable=True),
    sa.Column('date_prochain_rappel', sa.Date(), nullable=True),
    sa.Column('veterinaire_responsable', sa.String(length=100), nullable=True),
    sa.Column('cout', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['maladie_id'], ['maladies.id'], ),
    sa.ForeignKeyConstraint(['vaccin_id'], ['vaccins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccinations_animal_id'), 'vaccinations', ['animal_id'], unique=False)
    op.create_table('video_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('enclos_id', sa.Integer(), nullable=True),
    sa.Column('debut', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duree_secondes', sa.Float(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('ia_anomalie_detectee', sa.Boolean(), nullable=True),
    sa.Column('ia_anomalie_type', sa.String(length=100), nullable=True),
    sa.Column('ia_confiance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['enclos_id'], ['enclos.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_quality_alertes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('water_quality_id', sa.Integer(), nullable=False),
    sa.Column('parametre', sa.String(length=50), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('seuil', sa.Float(), nullable=False),
    sa.Column('niveau', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('traitee', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['water_quality_id'], ['water_qualities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('destinataire', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('erreur_message', sa.Text(), nullable=True),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('naissances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mere_id', sa.Integer(), nullable=False),
    sa.Column('pere_bovin_id', sa.Integer(), nullable=True),
    sa.Column('pere_ovin_id', sa.Integer(), nullable=True),
    sa.Column('pere_caprin_id', sa.Integer(), nullable=True),
    sa.Column('animal_ne_id', sa.Integer(), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('poids_naissance', sa.Float(), nullable=True),
    sa.Column('sexe', sa.String(length=10), nullable=False),
    sa.Column('complications', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_ne_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['mere_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['pere_bovin_id'], ['bovins.id'], ),
    sa.ForeignKeyConstraint(['pere_caprin_id'], ['caprins.id'], ),
    sa.ForeignKeyConstraint(['pere_ovin_id'], ['ovins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naissances_animal_ne_id'), 'naissances', ['animal_ne_id'], unique=False)
    op.create_index(op.f('ix_naissances_mere_id'), 'naissances', ['mere_id'], unique=False)
    op.create_table('pesees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('lot_entomo_id', sa.Integer(), nullable=True),
    sa.Column('lot_avicole_id', sa.Integer(), nullable=True),
    sa.Column('date_pesee', sa.Date(), nullable=False),
    sa.Column('poids', sa.Float(), nullable=False),
    sa.Column('methode', sa.String(length=50), nullable=True),
    sa.Column('video_record_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animaux.id'], ),
    sa.ForeignKeyConstraint(['lot_avicole_id'], ['avicoles.id'], ),
    sa.ForeignKeyConstraint(['lot_entomo_id'], ['entomoculture_lots.id'], ),
    sa.ForeignKeyConstraint(['video_record_id'], ['video_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesees_animal_id'), 'pesees', ['animal_id'], unique=False)
    op.create_index(op.f('ix_pesees_date_pesee'), 'pesees', ['date_pesee'], unique=False)
    op.create_index(op.f('ix_pesees_lot_avicole_id'), 'pesees', ['lot_avicole_id'], unique=False)
    op.create_index(op.f('ix_pesees_lot_entomo_id'), 'pesees', ['lot_entomo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pesees_lot_entomo_id'), table_name='pesees')
    op.drop_index(op.f('ix_pesees_lot_avicole_id'), table_name='pesees')
    op.drop_index(op.f('ix_pesees_date_pesee'), table_name='pesees')
    op.drop_index(op.f('ix_pesees_animal_id'), table_name='pesees')
    op.drop_table('pesees')
    op.drop_index(op.f('ix_naissances_mere_id'), table_name='naissances')
    op.drop_index(op.f('ix_naissances_animal_ne_id'), table_name='naissances')
    op.drop_table('naissances')
    op.drop_table('alert_history')
    op.drop_table('water_quality_alertes')
    op.drop_table('video_records')
    op.drop_index(op.f('ix_vaccinations_animal_id'), table_name='vaccinations')
    op.drop_table('vaccinations')
    op.drop_table('recettes')
    op.drop_table('piscicoles')
    op.drop_table('ovins')
    op.drop_index(op.f('ix_mortalites_animal_id'), table_name='mortalites')
    op.drop_table('mortalites')
    op.drop_table('entomoculture_cycles')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_comptages_odoni_timestamp'), table_name='comptages_odoni')
    op.drop_table('comptages_odoni')
    op.drop_table('caprins')
    op.drop_table('bovins')
    op.drop_table('avicoles_productions')
    op.drop_table('avicoles_mortalites')
    op.drop_index(op.f('ix_alimentations_lot_entomo_id'), table_name='alimentations')
    op.drop_index(op.f('ix_alimentations_date'), table_name='alimentations')
    op.drop_index(op.f('ix_alimentations_animal_id'), table_name='alimentations')
    op.drop_table('alimentations')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_water_qualities_timestamp'), table_name='water_qualities')
    op.drop_index(op.f('ix_water_qualities_enclos_id'), table_name='water_qualities')
    op.drop_table('water_qualities')
    op.drop_table('vaccins')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_roles')
    op.drop_table('retournements_compost')
    op.drop_table('reines')
    op.drop_table('references_hypotheses')
    op.drop_table('recoltes_miel')
    op.drop_table('pieges_odoni')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_entomoculture_lots_identification'), table_name='entomoculture_lots')
    op.drop_table('entomoculture_lots')
    op.drop_table('donnees_experimentales')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_bien_etre_indices_enclos_id'), table_name='bien_etre_indices')
    op.drop_index(op.f('ix_bien_etre_indices_date'), table_name='bien_etre_indices')
    op.drop_table('bien_etre_indices')
    op.drop_index(op.f('ix_avicoles_identification'), table_name='avicoles')
    op.drop_table('avicoles')
    op.drop_index(op.f('ix_animaux_identification'), table_name='animaux')
    op.drop_table('animaux')
    op.drop_index(op.f('ix_action_logs_user_id'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ruches')
    op.drop_table('roles')
    op.drop_table('references_vaccination')
    op.drop_table('references_seuils')
    op.drop_table('references_nutrition')
    op.drop_table('references_generales')
    op.drop_table('references_croissance')
    op.drop_table('rations_alimentaires')
    op.drop_table('maladies')
    op.drop_table('enclos')
    op.drop_table('composts')
    op.drop_table('bien_etre_criteres')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
